#!/usr/bin/env sh
# $0 is a script name,
# $1, $2, $3 etc are passed arguments
# $1 is our command
CMD=$1

case "$CMD" in
  'start' )
    npm start -- --address 0.0.0.0 --port 8082 --dbUrl "http://$COUCHDB_USER:$COUCHDB_PASSWORD@$COUCHDB_HOST:5984/"
    ;;

   * )
    # Run custom command. Thanks to this line we can still use
    # "docker run our_image /bin/bash" and it will work
    exec "$@"
    ;;
esac
